//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexCoders_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int Id { get; set; }
        public string userID { get; set; }
        public int workshopID { get; set; }
        public System.DateTime dateAndTime { get; set; }
        public string workshopName { get; set; }
    }
}
