//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexCoders_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Workshop
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Enter Workshop Name")]
        [Display(Name = "Name")]
        [StringLength(60, MinimumLength = 4)]
        public string WorkshopName { get; set; }


        [Required(ErrorMessage = "Enter Workshop Description")]
        [Display(Name = "Description")]
        [StringLength(500, MinimumLength = 15)]
        public string WorkShopDescription { get; set; }

        [Required(ErrorMessage = "Select Workshop Date and Time")]
        [Display(Name = "Date and Time")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy  hh:mm}")]
        public System.DateTime WorkshopDateTime { get; set; }

        [Required(ErrorMessage = "Enter the Name of City")]
        [Display(Name = "City")]
        [StringLength(60, MinimumLength = 4)]
        public string City { get; set; }


        [Required(ErrorMessage = "Enter Location's Latitude")]
        [Display(Name = "Location Latitude")]
        public double Lat { get; set; }


        [Required(ErrorMessage = "Enter Location's Longitude")]
        [Display(Name = "Location Longitude")]
        public double Long { get; set; }


        [Required(ErrorMessage = "Enter the Workshops's Capicity")]
        [Display(Name = "Capacity")]
        [DataType(DataType.PhoneNumber)]
        [Range(1, 100)]
        public int Capicity { get; set; }


        [Required(ErrorMessage = "Enter Image URL")]
        [Display(Name = "Image URL")]
        [Url]
        public string ImageURL { get; set; }
    }
}
